### ISSUE TITLE
Comand is not installed

### ISSUE THREAD

**Issue by pepe** [andrewchambers/jfmt#1]
After running `jpm install https://github.com/andrewchambers/jfmt.git` everything seems to complete OK, but no `jfmt` command is installed in the `janet/bin`.

**Comment by andrewchambers** [comment]
did you find a solution?

**Comment by pepe** [comment]
No but it is not jfmt problem 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
